import type { Metadata } from 'next';
import './globals.scss';
import { ReactElement, ReactNode } from 'react';
import Header from './components/Header/Header';
import styles from './layout.module.scss';
import ReduxProvider from '@/providers/ReduxProvider';
import DataLoader from '@/app/components/DataLoader/DataLoader';
import { PrimeReactProvider } from 'primereact/api';
import 'primereact/resources/themes/saga-blue/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';
import { MessageProvider } from '@/providers/MessageProvider';
import FooterWrapper from './components/FooterWrapper/FooterWrapper';
import { SupportProvider } from '@/providers/SupportProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): ReactElement {
  return (
    <html lang="uk">
      <body className={styles.body}>
        <ReduxProvider>
          <PrimeReactProvider>
            <MessageProvider>
              <SupportProvider>
                <DataLoader />
                <div className={styles.body__container}>
                  <Header />
                  <div className={styles.body__inner}>{children}</div>
                  <FooterWrapper />
                </div>
              </SupportProvider>
            </MessageProvider>
          </PrimeReactProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
