export enum ToastKeysEnum {
  LOGIN = 'login',
  EMAIL_CONFIRMATION = 'email confirmation',
  PASSWORD_RESET_CONFIRMATION = 'password reset confirmation',
  REGISTRATION = 'registration',
  GOOGLE = 'google',
  CHANGE_EMAIL = 'change email',
  CONFIRM_EMAIL = 'confirm email',
  EDUCATION = 'education',
  HARD_SKILL = 'hark skill',
  SOCIAL = 'social',
  SOFT_SKILL = 'soft skill',
  USER_NAME = 'user name',
  RESET_PASSWORD = 'reset password',
  DISCORD = 'discord',
  PARTICIPATION_REQUEST = 'participation request',
  PARTICIPATION_INVITE = 'participation invite',
  NEW_PROJECT = 'new project',
  SUPPORT = 'support',
  DELETE_EDUCATION = 'delete education',
  DELETE_HARD_SKILL = 'delete hark skill',
  DELETE_SOCIAL = 'delete social',
  DELETE_SOFT_SKILL = 'delete soft skill',
  SAVE_CHANGES = 'save changes',
  USERS = 'users',
  COPY = 'copy',
}
