name: Pull Request Checks
on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 26
          cache: npm

      - run: npm ci
      - run: npm run lint:frontend
      - run: npm run lint:backend
      - run: npm run build
